### ISSUE TITLE
Create a one-to-one connection between Doctor and Specialty 

### ISSUE THREAD

**Issue by crex424** [crex424/EasyAppointmentManager#52] opened 2023-05-01 20:59 UTC
Create a one-to-many connection between Doctor and Specialty

**Comment by crex424** [comment] 2023-05-03 05:16
@TungKimProgrammer Hello,
Whenever I update the database I always get the error "'FK_Clinic_Location_LocationID' is not a constraint.
Could not drop constraint. See previous errors." I am wondering if you are running into the same issue or not?

**Comment by TungKimProgrammer** [comment] 2023-05-04 22:47
Yes, I have the same issue but somehow I found a way to fix it. Let me create a new issue to work with it and merge it to master.

**Comment by TungKimProgrammer** [comment] 2023-05-04 22:56
what branch were you in? I could checkout and take a look

**Comment by crex424** [comment] 2023-05-04 23:20
I am in the Campbell-Issue#52-OneToManyRelationshipBetweenDoctorSpecialty branch. I also not sure if I am connecting Doctor class to Specialty class correctly, though it looks correct.

**Comment by TungKimProgrammer** [comment] 2023-05-05 01:13
"'FK_Clinic_Location_LocationID' is not a constraint.
This error was caused by me, I guess, when I refactored some code.
You might want to delete the EasyAppointmentManager database in SQLServer Object Explorer and Add a new Migration and then Update-Database to see if it works

**Comment by TungKimProgrammer** [comment] 2023-05-05 01:52
I fixed the DB errors. After the pending Pull Request is merged, you could merge the master to your current branch.

**Comment by crex424** [comment] 2023-05-05 03:24
Thank you very much.

**Comment by crex424** [comment] 2023-05-05 03:37
@TungKimProgrammer Does a one-to-many relationship between Doctor and Specialty work for you, or do you want me to make it a one-to-one relationship to make it more simple?

**Closed** 2023-05-06 05:17 UTC
Labels: enhancement
